---
- name: Install dependencies
  become: yes
  apt: pkg=python-pip state=installed

- name: install flask with pip
  pip: name=flask

- name: copy images app
  copy: src=images-app dest=/home/vagrant/ owner=vagrant group=vagrant mode=0755

- name: Copy Upstart configuration
  template: src=img-panda.upstart.j2 dest=/etc/init/img-panda.conf

- name: Validating that server is running
  service: name=img-panda state=started
